CREATE TABLE IF NOT EXISTS traders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trader_id VARCHAR(32) NOT NULL UNIQUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trader_id BIGINT NOT NULL,
    stock VARCHAR(16) NOT NULL,
    sector VARCHAR(32) NOT NULL,
    quantity INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_positions_trader FOREIGN KEY (trader_id) REFERENCES traders(id),
    CONSTRAINT uk_positions_trader_stock UNIQUE (trader_id, stock),
    CONSTRAINT ck_positions_quantity_non_negative CHECK (quantity >= 0)
);

CREATE TABLE IF NOT EXISTS trade_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trader_id BIGINT NOT NULL,
    stock VARCHAR(16) NOT NULL,
    sector VARCHAR(32) NOT NULL,
    quantity INTEGER NOT NULL,
    side VARCHAR(8) NOT NULL,
    status VARCHAR(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trade_orders_trader FOREIGN KEY (trader_id) REFERENCES traders(id),
    CONSTRAINT ck_trade_orders_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_trade_orders_side CHECK (side IN ('BUY', 'SELL')),
    CONSTRAINT ck_trade_orders_status CHECK (status IN ('PENDING', 'FILLED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_trade_orders_trader_status ON trade_orders(trader_id, status);
CREATE INDEX IF NOT EXISTS idx_trade_orders_trader_stock_status_side ON trade_orders(trader_id, stock, status, side);
